### ISSUE TITLE
https://tvlistings.zap2it/...closed

### ISSUE THREAD

**Issue by darkmaller1138** [jef/zap2xml#15]
The original https://tvlistings.zap2it/ is no longer available, as the original media group shut down the site.

https://tvlistings.gracenote.com/grid-affiliates.html?aid=lat
Seems to be the same site, the same username and password work, is it possible for me to update the docker?

**Comment by victorbutler** [comment]
Should probably generate a new up-to-date image, but if this is all you need for now, you can download the fixed perl script (refer to issue #12) and mount it into your container.

1. [Download fixed perl script](https://github.com/pragmaticjim/zap2xml/raw/refs/heads/main/zap2xml.pl) from pragmaticjim's fork (make sure it uses LF line endings, not CRLF)
2. Volume mount that file to `/opt/zap2xml.pl` with proper permissions (chmod 755 or just +x permissions)

---

```yml
  zap2xml:
    container_name: zap2xml
    image: ghcr.io/jef/zap2xml:latest
    environment:
      OPT_ARGS: >-
        -I -D -U -C /config/.zap2xmlrc
      SLEEPTIME: 86400 # 24 hours in seconds
    volumes:
      - /zap2xml/config:/config
      - /zap2xml/xmltv:/xmltv
      - /zap2xml/zap2xml.pl:/opt/zap2xml.pl
    restart: unless-stopped
```

Should work like normal, albeit kinda silly. Docker image update is def preferred.
